### ISSUE TITLE
Does Hugo Atlantic Theme have the following features?

### ISSUE THREAD

**Issue by Josh-BI-UK** [zerostaticthemes/hugo-atlantic-theme#6]
Hi @JugglerX,

I would love to implement your template for a personal blog. However, there are a few features from another template which I would like to use within the Atlantic theme.

P.s I'm super new to the Hugo framework and only want to create a personal blog about data science. So please excuse me if I'm asking silly questions.

### **Does Hugo Atlantic Theme have the following features?**:

- A & B) I would like to replace the three-bar gradient menu with a static top-site navigation similar to the C) [hugo-theme-puppet](https://hugo-theme-puppet.netlify.app/) theme
- D) Does the Atlantic theme have a search feature similar to the one shown in the screenshot below?
- E) Can a side menu be created on the blog template page featuring:
   -  D) a tag section? 
   - F) Section which could host a list of previous blogs, ads or other sections of the website.
   - G) Other useful items like social media icons etc.

![does-template-have the following-features](https://user-images.githubusercontent.com/59780902/205514448-fc525f23-7530-422c-a4f7-6c7c693f4eb5.png)

I would really appreciate your advice. Thank you

**Comment by JugglerX** [comment]
Hi @Josh-BI-UK 

In answer to your questions

A & B) The theme does not have a regular menu out of the box
D) This theme has no search feature
E) This theme does not support those features in the sidebar
